DROP TABLE if EXISTS fileInfo;

CREATE TABLE fileInfo(
  id BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  fileName VARCHAR NOT NULL,
  fileOriginalFileName VARCHAR NOT NULL,
  filePath VARCHAR NOT NULL,
  fileType VARCHAR NOT NULL,
  fileSize BIGINT NOT NULL,
  createTime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  createUser VARCHAR NOT NULL
);